In [ ]:
#1.PYTHON LIBRARY:
'''Normally, a library is a collection of books or is a room or place where many books are stored to be used later. 
Similarly, in the programming world, a library is a collection of precompiled codes that can be used later on in a program 
for some specific well-defined operations. Other than pre-compiled codes, a library may contain documentation,
configuration data, message templates, classes, and values, etc.

A Python library is a collection of related modules. 
It contains bundles of code that can be used repeatedly in different programs. 
It makes Python Programming simpler and convenient for the programmer.
As we don’t need to write the same code again and again for different programs. 
Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.'''

#USES:
'''As we write large-size programs in Python, we want to maintain the code’s modularity.
For the easy maintenance of the code, we split the code into different parts and we can use that code later ever we need it.
In Python, modules play that part. Instead of using the same code in different programs and making the code complex,
we define mostly used functions in modules and we can just simply import them in a program wherever there is a requirement.
We don’t need to write that code but still, we can use its functionality by importing its module.
Multiple interrelated modules are stored in a library. And whenever we need to use a module, we import it from its library. 
In Python, it’s a very simple job to do due to its easy syntax. We just need to use import.'''

In [ ]:
#2.PYTHON LIST:

'''A Python list is a collection that is ordered and changeable. In Python, lists are written with square brackets. 

Some important points about Python Lists:

The list can be homogeneous or heterogeneous.
Element-wise operation is not possible on the list.
Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
Elements of a list need not be contiguous in memory.

#PYTHON NUMPY:
NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical
and other types of operations on large numbers of data. 
Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
Numpy is not another programming language but a Python extension module. It provides fast and efficient
operations on arrays of homogeneous data. 

Some important points about Numpy arrays:

We can create an N-dimensional array in Python using Numpy.array().
The array is by default Homogeneous, which means data inside an array must be of the same Datatype.
(Note You can also create a structured array in Python).
Element-wise operation is possible.
Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have
the same number of columns. A three-dimensional array must have the same number of rows and columns on each card.'''


In [4]:
#3.SIZE,SHAPE,DIMENSION
import numpy as np
data = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arrData = np.array(data)

print(data)
print(arrData.size)
print(arrData.shape)

arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('2D Numpy Array')
print(arr2D)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
12
(3, 4)
2D Numpy Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#4.
import pandas as pd

df = pd.DataFrame([
            [1, 2, 1], [1, 3, 2], [4, 6, 3], [4, 3, 4], [5, 4, 5]
        ], columns=['A', 'B', 'C'])

df

A  B  C
0  1  2  1
1  1  3  2
2  4  6  3
3  4  3  4
4  5  4  5

In [11]:
#5.
import numpy as np
 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
 
# Access the ith column of a 2D NumPy array
column_i = arr.T[2]
 
#printing the column
print(column_i)

[ 3  7 11]


In [16]:
#6.
test_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] 
 
# printing original list 
print("The original list is : " + str(test_list)) 
 
# Odd elements indices
# using loop 
res = [] 
for idx, ele in enumerate(test_list): 
    if ele % 2 != 0: 
        res.append(idx) 
         
# printing result 
print("Indices list Odd elements is : " + str(res)) 

The original list is : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Indices list Odd elements is : [0, 2, 4, 6, 8, 10]


In [ ]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^
'''Generate sequence of values (in some range) you would like to randomly select into matrix.
Take randomly some number of elements from this sequence to new sequence.
From this new sequence make matrix with wanted shape.
import numpy as np
from random import sample

#step one
values = range(0,11)
#step two
random_sequence = sample(values, 9)
#step three
random_matrix = np.array(random_sequence).reshape(3,3)'''

In [ ]:
#8.
'''In summary, while both np.random.rand() and np.random.randn() are used for generating random numbers in NumPy,
they operate differently and serve different purposes. np.random.rand() produces random numbers
from a uniform distribution over the interval [0, 1), while np.random.randn()
generates random numbers from a standard normal distribution.'''

In [1]:
#9.changing dimension
import numpy as np
 
 
def main():
 
    # initialising array
    print('Initialised array')
    gfg = np.array([1, 2, 3, 4])
    print(gfg)
 
    # checking current shape
    print('current shape of the array')
    print(gfg.shape)
     
    # modifying array according to new dimensions
    print('changing shape to 2,2')
    gfg.shape = (2, 2)
    print(gfg)
 
if __name__ == "__main__":
    main()

Initialised array
[1 2 3 4]
current shape of the array
(4,)
changing shape to 2,2
[[1 2]
 [3 4]]


In [3]:
#10.transpose
import numpy as np
 
# making a 3x3 array
gfg = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
 
# before transpose
print(gfg, end ='\n\n')
 
# after transpose
print(gfg.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
#11.1.imultiplication
import numpy as np

a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(np.multiply(a1, a2))


#2.matrix multiplication
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
# 3x4 matrix
Y = [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)


#3.add two matrix
X = [[1,2,3],
    [5,6,7],
    [9,10,11]]

Y = [[1,2,3],
    [5,6,7],
    [9,10,11]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):   
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)
    
    
#4.SUBRACT
# Python program explaining
# numpy.subtract() function
 
import numpy as geek
 
in_arr1 = geek.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
in_arr2 = geek.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
  
print ("1st Input array : ", in_arr1)
print ("2nd Input array : ", in_arr2)
  
   
out_arr = geek.subtract(in_arr1, in_arr2) 
print ("Output array: ", out_arr) 



#5.divide
import numpy as np 
  
# input_array 
arr1 = [2, 27, 2, 21, 23] 
arr2 = [2, 3, 4, 5, 6] 
print ("arr1         : ", arr1) 
print ("arr2         : ", arr2) 
  
# output_array 
out = np.divide(arr1, arr2) 
print ("\nOutput array : \n", out)


[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[38, 44, 50, 56]
[98, 116, 134, 152]
[158, 188, 218, 248]
[2, 4, 6]
[10, 12, 14]
[18, 20, 22]
1st Input array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2nd Input array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Output array:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]


In [13]:
#12.
'''The ndarray.byteswap() method swaps the bytes of the array elements.
It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.

Note: byteswap() method does not work on arrays of strings.'''

#Example
# Python program explaining  
# byteswap() function  
import numpy as geek 
  
# a is an array of integers. 
a = geek.array([1, 256, 100], dtype = np.int16) 
   
print(a.byteswap(True)) 

[  256     1 25600]


In [19]:
#13.
'''We use numpy.linalg.inv() function to calculate the inverse of a matrix.
The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.'''

import numpy as np 

x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
(print (x) )
(print (y) )
print( np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [21]:
#14.
'''The numpy.reshape() function shapes an array without changing the data of the array.'''
# numpy.reshape() method 
  
import numpy as geek 
  
# array = geek.arrange(8)  
# The 'numpy' module has no attribute 'arrange' 
array1 = geek.arange(8) 
print("Original array : \n", array1) 
  
# shape array with 2 rows and 4 columns 
array2 = geek.arange(8).reshape(2, 4) 
print("\narray reshaped with 2 rows and 4 columns : \n",  
      array2) 
  
# shape array with 4 rows and 2 columns 
array3 = geek.arange(8).reshape(4, 2) 
print("\narray reshaped with 4 rows and 2 columns : \n", 
      array3) 
  
# Constructs 3D array 
array4 = geek.arange(8).reshape(2, 2, 2) 
print("\nOriginal array reshaped to 3D : \n", 
      array4) 

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [22]:
#15.
'''Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops.
This is because NumPy is implemented in C Programming, which is a very efficient language.

It does this without making needless copies of data which leads to efficient algorithm implementations.
But broadcasting over multiple arrays in NumPy extension can raise cases where
broadcasting is a bad idea because it leads to inefficient use of memory that slows down the computation.

The resulting array returned after broadcasting will have the same number of dimensions 
as the array with the greatest number of dimensions.'''
import numpy as np 
  
a = np.array([5, 7, 3, 1]) 
b = np.array([90, 50, 0, 30]) 
  
# array are compatible because of same Dimension 
c = a * b 
print(c) 


[450 350   0  30]


      ********************THANK YOU*****************